language: node_js
node_js:
  - '4.6.0'
before_install:
  - 'npm install -g bower gulp'
  - 'npm install'
  - 'bower install'
script: gulp test
cache:
  directories:
    - node_modules
    - app/bower_components
